name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python tooling
        run: |
          python -m pip install --upgrade pip
          pip install ruff black isort

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (black)
        run: black --check .

      - name: Import sort check (isort)
        run: isort --check-only .

      - name: Validate app structure
        run: |
          test -f hooks.py
          test -f MANIFEST.in
          test -f setup.py
          echo "Structure OK"

  # Optional: Node step if you keep any frontend tooling in the app itself
  node-audit:
    runs-on: ubuntu-latest
    if: ${{ hashFiles('package.json') != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"
      - name: Install deps
        run: |
          if [ -f yarn.lock ]; then yarn install --frozen-lockfile; else npm ci; fi
      - name: Build (optional)
        run: |
          if [ -f package.json ]; then
            if jq -e '.scripts.build' package.json > /dev/null 2>&1; then
              yarn build || npm run build
            else
              echo "No build script"
            fi
          fi
